config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about'=>'homes#about',as: 'about'

  resources :users, only:[:index, :show, :edit, :update]
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_one_attached :profile_image

  validates :title, presence: true
  validates :body,
  presence: true,
  length: { maximum: 200 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 } , uniqueness: true
  validates :introduction,length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to books_path unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

 def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(resource), notice: 'Welcome! You have signed up successfully.'
    end
 end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:success] = "You have updated user successfully."
      redirect_to user_path(@user.id)
     else
       render :edit
     end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <%= form_with model: @book do |f| %>
          <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, id:"book_title", class: 'form-control book_title' %>
          </div>
          <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, id:"book_body", class: 'form-control book_body' %>
          </div>
          <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
          </div>
        <% end %>

        <%= link_to 'Show', book_path(@book) %>

        <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100, 100) %>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>

        <div class="row">
          <%= link_to edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block' do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
            <%= f.text_field :title, id:"book_title", class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, id:"book_opinion", class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: 'btn btn-success' %>
        </div>
        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                   <%= image_tag book.user.get_profile_image(100, 100) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <%= flash[:success] %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">

        <%= render 'users/userinfo', user: @user %>

        <h2 class="mt-3">New book</h2>
          <%= form_with model: @books do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, id:"book_title", class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, id:"book_body", class: 'form-control book_body' %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: 'btn btn-success' %>
          </div>
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                  <%= image_tag @book.user.get_profile_image(100, 100) %>
                  <br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book.id), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？",
              class: 'btn btn-sm btn-danger' %></td>
            <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to<i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
          <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
          <P>you can share and exchange your opinions , inpressions , and emotions</P>
          <p>about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </diV>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            </div>
          </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-users"></i>Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                 <i class="fas fa-sign-out-alt"></i>Log out
                <% end %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= flash[:notice] %>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
    <%= image_tag user.get_profile_image(100, 100) %>
      <table class="table">
        <tr>
            <th>name</th>
            <th><%= user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
            </tr>
      </table>

        <div class="row">
          <% if @user.id == current_user.id %>
           <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
             <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, id:"user_name", class: 'form-control name' %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.file_field :profile_image,  accept: "image/*", class: 'form-control-file user_image' %>
          </div>
          <div class="form-group">
            <label for="user_inputIntroduction">Introduction</label>
            <%= f.text_area :introduction,  id:"user_inputintroduction", class: 'form-control introduction' %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <%= render 'users/userinfo', user: @user %>

          <h2 class="mt-3">New book</h2>
          <%= form_with model: @book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, id:"book_title", class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, id:"book_opinion", class: 'form-control book_body' %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: 'btn btn-success' %>
          </div>
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= image_tag user.get_profile_image(80, 80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <%= flash[:success] %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <%= render 'users/userinfo', user: @user %>

        <h2 class="mt-3">New book</h2>
          <%= form_with model: @book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title,id:"book_title", class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, id:"book_body", class: 'form-control book_body' %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: 'btn btn-success' %>
          </div>
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(80, 80) %>
              <% end %>
              </td>
              <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>